# apiVersion v2 is Helm 3
---
apiVersion: v2
name: face-api
home: https://faceapi.regulaforensics.com/
version: 0.1.1
appVersion: 4.1.99.375
description: Face Recognition Service. On-premise and cloud integration
icon: https://secure.gravatar.com/avatar/71a5efd69d82e444129ad18f51224bbb.jpg
keywords:
  - regula
  - face-api
  - regulaforensics
dependencies:
  - name: postgresql
    version: 10.16.2
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: milvus
    version: 3.0.29
    repository: "https://milvus-io.github.io/milvus-helm"
    condition: milvus.enabled
maintainers:
  - email: support@regulaforensics.com
    name: Regula Forensics Support
    url: https://support.regulaforensics.com
type: application
